app:
  browser: firefox
  url: http://automationpractice.com/index.php
hub:
  protocol: http
  host: localhost
  port: 4444

spring:
  profiles:
    active: remote
  jpa:
    defer-datasource-initialization: true