project:
  name: auto-bot
  browser: chrome

  reportPath: /results/reports/
  reportName: ${project.name}
  reportFormat: .html

  logPath: /results/logs/
  logName: ${project.name}
  logFormat: .log

  snapPath: /results/reports/snaps/
  dataPath: /resources/testdata/

spring:
  profiles:
    active: local,flight,visa
  jpa:
    defer-datasource-initialization: true