project:
  name: auto-bot
  browser: chrome

  reportPath: /results/reports/
  reportName: ${project.name}
  reportFormat: .html

  logPath: /results/logs/
  logName: ${project.name}
  logFormat: .log

  snapPath: /results/reports/snaps/
  dataPath: /resources/testdata/

visa:
  url: https://vins-udemy.s3.amazonaws.com/sb/visa/udemy-visa.html
  header: VISA Registration Form
  subHeader: Fill out the form carefully for registration

flight:
  url: https://vins-udemy.s3.amazonaws.com/docker/docker-book-flight.html
  header: Docker Flight Booking Application
  subHeader: User Registration Form

spring:
  profiles:
    active: local
  jpa:
    defer-datasource-initialization: true